#name of the workflow
name: Recent x

on:
  schedule:
    - cron: '*/4 * * * *'  # Update tweets every 30 minutes. You can adjust the frequency as needed.

jobs:
  update_tweets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can adjust the Node.js version if needed.

    - name: Install Dependencies
      run: npm install tweet-update

    - name: Fetch and Update Tweets
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: npx tweet-update --username codewithdev --count 5 --output README.md --placeholder "MY XES"
